clientid :
clientsecret : 
scopes :
  - https://www.googleapis.com/auth/spreadsheets
redirecturl : urn:ietf:wg:oauth:2.0:oob
endpoint :
  authurl : https://accounts.google.com/o/oauth2/v2/auth
  tokenurl : https://www.googleapis.com/oauth2/v4/token
